check bannerImage & welcomeBannerImage
dan-snelson/Setup-Your-Mac pull request #21
Opened 2023-04-07 22:13 UTC by amadotejada

The Dialog fails to open if the banner/welcome images are not available. We use this to test the image URLs and set an alternative image if the default fails. Folks can add a second custom image as a backup.

2023-04-07 22:21 UTC, dan-snelson commented
Thanks, @amadotejada. 

https://github.com/bartreardon/swiftDialog/issues/239

2023-04-07 23:48 UTC, dan-snelson reviewed
@amadotejada:

The `development` branch is now at `1.10.0-rc4`; will you please update your side to this version and re-submit?

Thanks.


--
Dan

2023-04-07 23:48 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +    echo "welcomeBannerImage is available"
Please replace `echo` with `updateScriptLog "WELCOME DIALOG: …"

2023-04-07 23:48 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +    echo "welcomeBannerImage is not available, using alternative image"
Please replace `echo` with `updateScriptLog "WELCOME DIALOG: …"

2023-04-07 23:48 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +    echo "bannerImage is available"
Please replace `echo` with `updateScriptLog "WELCOME DIALOG: …"

2023-04-07 23:48 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +    echo "bannerImage is not available, using alternative image"
Please replace `echo` with `updateScriptLog "WELCOME DIALOG: …"

2023-04-08 00:07 UTC, amadotejada commented
@dan-snelson

Updated to 1.10.0-rc4 and replaced the `echo` lines. 

Thank you

2023-04-08 02:34 UTC, dan-snelson requested changes
@amadotejada:

Perhaps it's me, but it _appears_ that this is still committed against `1.9.0`:

https://github.com/amadotejada/Setup-Your-Mac/blob/647241c9c263adf7ef7eca582390137bf7a25b74/Setup-Your-Mac-via-Dialog.bash#L36

2023-04-08 07:00 UTC, dan-snelson commented
Closing; see [Pull No. 22](https://github.com/dan-snelson/Setup-Your-Mac/pull/22).

2023-04-08 07:00 UTC, closed without merging