Setup your mac 1.12.4
dan-snelson/Setup-Your-Mac pull request #90
Opened 2023-08-25 16:49 UTC by AndrewMBarnett

Added user input with more pre-fill info, add pre-fill info to infobox and create receipts for Jamf Extension Attributes.

2023-08-26 09:31 UTC, dan-snelson requested changes
Thanks for the PR, @AndrewMBarnett; comments in-line.

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +scriptLog="${4:-"/var/log/(LOG LOCATION)"}"                        # Parameter 4: Script Log Location [ /var/log/org.churchofjesuschrist.log ] (i.e., Your organization's default location for client-s
No plans to change

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +prefillEmail="true"             # prefills email based on username and email ending variable
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +prefillComputerName="true"      # prefills based on current computer name
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +promptForAssetTag="false"
Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +promptForRoom="false"
Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +promptForBuilding="false"
Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +promptForDepartment="false"
Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +buildingsListRaw="N/A"
No plans to change; needed for initial demo

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +departmentListRaw="N/A"
No plans to change; needed for initial demo

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +emailEnding=""
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +brandingBanner=""
No plans to change; needed for initial demo

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +brandingIconLight=""
No plans to change; needed for initial demo

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +brandingIconDark=""
No plans to change; needed for initial demo

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +
No plans to include breadcrumb-creation in SYM

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +ComputerName=$(scutil --get ComputerName)
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +welcomeTitle="Welcome to your new ${modelName} ${loggedInUserFirstname}!"
No plans to change; Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +welcomeMessage="Please enter the **required** information for your ${modelName}, select your preferred **Configuration** then click **Continue** to start applying settings to your new Mac. \n\nOnce c
`${supportKB}` variable was removed; no plans to change

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +    welcomeMessage+="  \n\n#### Configurations  \n\n- **${configurationOneName}:** ${configurationOneDescription}  \n\n- **${configurationTwoName}:** ${configurationTwoDescription}  \n\n- **${configu
No plans to change; Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +if [ "$prefillEmail" == "true" ]; then emailPrefil=',"value" : "'${loggedInUser}${emailEnding}'"'; fi
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +        "prompt" : "Email Address"'${emailPrefil}',
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +if [ "$promptForComputerName" == "true" ]; then compNameJSON='{ "title" : "Computer Name","required" : false,"prompt" : "Computer Name"'${computerNamePrefill}'},'; fi
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +setupYourMacPolicyArrayIconPrefixUrl="https://usw2.ics.services.jamfcloud.com/icon/hash_"
Looks like Jamf Cloud customers are being migrated

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +        updateScriptLog "Failed policies detected …"
So, _that's_ how "policies" is spelled?

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +            if [[ "${webhookStatus}" == "FailuresDetected" ]] ; then echo ${webhookStatus} > $receipt_path; fi
No plans to include breadcrumb creation in SYM

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +            dialogUpdateFailure "message: A failure has been detected, ${loggedInUserFirstname}. \n\nPlease complete the following steps:\n1. Reboot and login to your ${modelName}  \n2. Open to Self
No plans to change; Appears to be personal preference

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +            if [[ "${webhookStatus}" == "Successful" ]] ; then echo ${webhookStatus} > $receipt_path; fi
No plans to include breadcrumb creation in SYM

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +                            "text": "*Policy Failures:*\n${jamfProPolicyNameFailures}"
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +            "name": "Policy Failures",
Interesting

2023-08-26 09:31 UTC, dan-snelson commented on Setup-Your-Mac-via-Dialog.bash
> +if [[ -n ${email} ]]; then infobox+="**Email:**  \n$email  \n\n" ; fi
Interesting

2023-08-28 14:22 UTC, dan-snelson reviewed
@AndrewMBarnett:

I'm still observing:
- Unresolved conversations (29)
- Resolved conversations (0)

2023-08-28 14:51 UTC, AndrewMBarnett commented
Sorry about that, didn't mean to re-request. Thanks for looking it over!

2023-08-30 06:42 UTC, dan-snelson commented
@AndrewMBarnett:

Ah, OK.

I recommend **this** PR be closed and you can re-submit another with just the additions.

2023-09-09 10:19 UTC, dan-snelson commented
@AndrewMBarnett:

I'm going to close this PR; please feel free to submit another one with just your additions.

Thanks.

2023-09-09 10:19 UTC, closed without merging